-- DROP TABLE IF EXISTS USERS;
-- CREATE TABLE USERS(
--	user_name char(20) not null primary key,
--    password char(40) not null,
--     role char(10)
-- );
--
-- DROP TABLE IF EXISTS MESSAGES;
-- CREATE TABLE MESSAGES(
-- 	ID int NOT NULL AUTO_INCREMENT primary key,
-- 	user_name char(20) not null,
--     message char(250) not null,
--     time datetime
-- );

